// This file is part of the uutils awk package.
//
// For the full copyright and license information, please view the LICENSE
// files that was distributed with this source code.


#[cfg(test)]
mod tests;

use core::str;
use std::{
    borrow::Cow,
    fmt::{Debug, Display},
    slice::SliceIndex,
};

use logos::Skip;
pub use logos::{Logos, Span, SpannedIter};
use memchr::{memchr, memchr3};
use thiserror::Error;

pub type Lexer<'a> = logos::Lexer<'a, Token<'a>>;
pub type Result<T, E = LexingError> = std::result::Result<T, E>;

// TODO: check wnat GNU does about potentially reserved `@ident`; add error branch if so.
#[derive(Logos, Debug, PartialEq)]
#[logos(utf8 = false)]
#[logos(skip("[ \t]+"))]
#[logos(skip(r"(\\\n)+"))]
#[logos(skip("#", skip_line))]
#[logos(extras = Context)]
#[logos(subpattern identifier = r"[a-zA-Z_][a-zA-Z0-9_]*")]
#[logos(error(LexingError, callback = |lex| LexingError::from(lex)))]
pub enum Token<'a> {
    #[regex(r"[0-9]+(\.[0-9]+)?([eE][+-]?[0-9]+)?", parse_float)]
    #[regex(r"\.[0-9]+([eE][+-]?[0-9]+)?", parse_float)]
    Number(f64),
    #[token("\"", parse_string)]
    String(Slice<'a>),
    #[token("BEGIN", accept_expression)]
    BeginPattern,
    #[token("END", accept_expression)]
    EndPattern,
    #[token("BEGINFILE", accept_expression)]
    BeginFilePattern,
    #[token("ENDFILE", accept_expression)]
    EndFilePattern,
    #[token("@load \"", parse_directive)]
    LoadDirective(Slice<'a>),
    #[token("@include \"", parse_directive)]
    IncludeDirective(Slice<'a>),
    #[token("@nsinclude \"", parse_directive)]
    NsIncludeDirective(Slice<'a>),
    #[regex("@namespace \"(?&identifier)\"", |lex| parse_ident(lex, 12..lex.slice().len() - 1))]
    NamespaceDirective(&'a str),
    #[token("@concurrent", accept_expression)]
    ConcurrentDirective,
    #[token("if", accept_expression)]
    If,
    #[regex(r"else\n*", accept_expression)]
    Else,
    #[token("switch", accept_expression)]
    Switch,
    #[token("case", accept_expression)]
    Case,
    #[token("default", accept_expression)]
    Default,
    #[regex(r"do\n*", accept_expression)]
    Do,
    #[token("while", accept_expression)]
    While,
    #[token("for", accept_expression)]
    For,
    #[token("in", accept_expression)]
    In,
    #[token("print", accept_expression)]
    Print,
    #[token("printf", accept_expression)]
    Printf,
    #[token("getline", accept_expression)]
    Getline,
    #[token("next", accept_expression)]
    Next,
    #[token("nextfile", accept_expression)]
    NextFile,
    #[token("exit", accept_expression)]
    Exit,
    #[token("break", accept_expression)]
    Break,
    #[token("continue", accept_expression)]
    Continue,
    #[token("return", accept_expression)]
    Return,
    #[token("delete", accept_expression)]
    Delete,
    #[token("function", accept_expression)]
    Function,
    #[token("NR", accept_expression)]
    NrVariable,
    #[token("NF", accept_expression)]
    NfVariable,
    #[token("FS", accept_expression)]
    FsVariable,
    #[token("RS", accept_expression)]
    RsVariable,
    #[token("OFS", accept_expression)]
    OfsVariable,
    #[token("ORS", accept_expression)]
    OrsVariable,
    #[token("FILENAME", accept_expression)]
    FilenameVariable,
    #[token("ARGC", accept_expression)]
    ArgcVariable,
    #[token("ARGV", accept_expression)]
    ArgvVariable,
    #[token("SUBSEP", accept_expression)]
    SubsepVariable,
    #[token("FNR", accept_expression)]
    FnrVariable,
    #[token("ARGIND")]
    ArgindVariable,
    #[token("OFMT", accept_expression)]
    OfmtVariable,
    #[token("RSTART", accept_expression)]
    RstartVariable,
    #[token("RLENGTH", accept_expression)]
    RlengthVariable,
    #[token("ENVIRON", accept_expression)]
    EnvironVariable,
    #[regex("(?&identifier)", Identifier::without_namespace)]
    #[regex(r"(?&identifier)::(?&identifier)", Identifier::with_namespace)]
    Identifier(Identifier<'a>),
    #[token("+", accept_expression)]
    Plus,
    #[token("-", accept_expression)]
    Minus,
    #[token("*", accept_expression)]
    Star,
    #[token("/", parse_regex_or_slash)]
    Slash,
    /// Not generated by Logos directly.
    Regex(Slice<'a>),
    #[token("%", accept_expression)]
    Percent,
    #[token("^", accept_expression)]
    Circumflex,
    #[token("++", accept_expression)]
    Increment,
    #[token("--", accept_expression)]
    Decrement,
    #[token("=", accept_expression)]
    Assignment,
    #[token("+=", accept_expression)]
    PlusAssign,
    #[token("-=", accept_expression)]
    MinusAssign,
    #[token("*=", accept_expression)]
    StarAssign,
    #[token("/=", accept_expression)]
    SlashAssign,
    #[token("%=", accept_expression)]
    PercentAssign,
    #[token("^=", accept_expression)]
    CaretAssign,
    #[token("==", accept_expression)]
    EqualTo,
    #[token("!=", accept_expression)]
    NotEqualTo,
    #[token("<", accept_expression)]
    LesserThan,
    #[token("<=", accept_expression)]
    LesserOrEqualThan,
    #[token(">", accept_expression)]
    GreaterThan,
    #[token(">=", accept_expression)]
    GreaterOrEqualThan,
    #[regex(r"&&\n*", accept_expression)]
    BooleanAnd,
    #[regex(r"\|\|\n*", accept_expression)]
    BooleanOr,
    #[token("!", accept_expression)]
    Negation,
    #[token("~", accept_expression)]
    Matching,
    #[token("!~", accept_expression)]
    NotMatching,
    #[token("|", accept_expression)]
    Pipe,
    #[token("|&", accept_expression)]
    DoublePipe,
    #[token(">>", accept_expression)]
    AppendPipe,
    #[regex(r"\?\n*", accept_expression)]
    QuestionMark,
    #[regex(r":\n*", accept_expression)]
    Colon,
    #[regex(r"\{\n*", accept_expression)]
    OpenBrace,
    #[token("}", accept_expression)]
    ClosedBrace,
    #[token("(", accept_expression)]
    OpenParent,
    #[token(")", accept_operator)]
    ClosedParent,
    #[token("[", accept_expression)]
    OpenBracket,
    #[token("]", accept_operator)]
    ClosedBracket,
    #[regex(r",\n*", accept_expression)]
    Comma,
    #[token("$", accept_expression)]
    Record,
    #[regex(r"\n+", accept_expression)]
    Newline,
    #[regex(";+", accept_expression)]
    Semicolon,
}

#[derive(Debug, Default, PartialEq, Eq)]
pub enum Context {
    #[default]
    AcceptExpression,
    AcceptOperator,
}

#[derive(Debug, Default, Error, Clone, PartialEq, Eq)]
pub enum LexingError {
    #[default]
    #[error("Unknown error")]
    Unknown,
    #[error("Unexpected token at {:?}: `{}`", .0, .1)]
    Unexpected(Span, String),
    #[error("Unterminated string at {:?}", .0)]
    UnterminatedString(Span),
    #[error("Unterminated regex at {:?}", .0)]
    UnterminatedRegex(Span),
    #[error("Unexpected End of File!")]
    UnexpectedEof,
}

#[derive(Debug, PartialEq, Eq, Clone, Copy)]
pub struct Identifier<'a> {
    pub namespace: Option<&'a str>,
    pub literal: &'a str,
}

impl From<&mut Lexer<'_>> for LexingError {
    fn from(lex: &mut Lexer<'_>) -> Self {
        Self::Unexpected(lex.span(), String::from_utf8_lossy(lex.slice()).to_string())
    }
}

fn skip_line(lex: &mut Lexer<'_>) -> Skip {
    lex.bump(memchr(b'\n', lex.remainder()).unwrap_or(lex.remainder().len()));
    logos::skip(lex)
}

fn parse_string<'a>(lex: &mut logos::Lexer<'a, Token<'a>>) -> Result<Slice<'a>> {
    parse_content::<false, false, '"'>(lex)
}

fn parse_regex_or_slash<'a>(lex: &mut logos::Lexer<'a, Token<'a>>) -> Result<Token<'a>> {
    match lex.extras {
        Context::AcceptExpression => {
            accept_operator(lex);
            parse_content::<false, true, '/'>(lex).map(Token::Regex)
        }
        Context::AcceptOperator => {
            accept_expression(lex);
            Ok(Token::Slash)
        }
    }
}

fn parse_directive<'a>(lex: &mut Lexer<'a>) -> Result<Slice<'a>> {
    parse_content::<true, false, '"'>(lex)
}

fn parse_content<'a, const MINIMAL: bool, const REGEX: bool, const DELIMITER: char>(
    lex: &mut Lexer<'a>,
) -> Result<Slice<'a>> {
    let rest = lex.remainder();
    let mut start = 0;
    let mut out: Cow<'a, [u8]> = Cow::Borrowed(&[]);

    while let Some(rel_i) = memchr3(b'\n', b'\\', DELIMITER as u8, &rest[start..]) {
        let i = start + rel_i;

        match rest[i] {
            d if d == DELIMITER as u8 => {
                // push remaining segment
                lex.bump(i + 1);
                if start == 0 {
                    out = Cow::Borrowed(&rest[..i]);
                } else {
                    out.to_mut().extend_from_slice(&rest[start..i]);
                }
                return Ok(Slice(out));
            }
            b'\\' => {
                out.to_mut().extend_from_slice(&rest[start..i]);
                let consumed = parse_escape::<MINIMAL, REGEX>(&rest[i..], out.to_mut())?;
                start = i + consumed;
            }
            _ => break,
        }
    }
    if REGEX {
        Err(LexingError::UnterminatedRegex(lex.span()))
    } else {
        Err(LexingError::UnterminatedString(lex.span()))
    }
}

fn parse_escape<const MINIMAL: bool, const REGEX: bool>(
    slice: &[u8],
    out: &mut Vec<u8>,
) -> Result<usize> {
    let mut count = 2;
    let is_oct = |x: char| ('0'..'8').contains(&x);
    let is_slice_oct = |i| slice.get(i).map(|&x| x as char).is_some_and(is_oct);
    let Some(to_escape) = slice.get(1).map(|x| *x as char) else {
        return Err(LexingError::UnexpectedEof);
    };

    if to_escape == '\n' {
        return Ok(count);
    }

    // On minimal, only drop backslash for '"' and '\n'
    let escaped = if MINIMAL && !matches!(to_escape, '"' | '\n') {
        out.push(b'\\');
        to_escape
    } else if MINIMAL {
        to_escape
    } else {
        match to_escape {
            c @ ('\\' | '"') if !REGEX => c,
            c @ ('[' | ']' | '{' | '}' | '(' | ')' | '*' | '+' | '^' | '$' | '.' | '?')
                if REGEX =>
            {
                out.push(b'\\');
                c
            }
            'a' => 7 as char,
            'b' => 8 as char,
            'f' => 12 as char,
            'n' => '\n',
            'r' => '\r',
            't' => '\t',
            'v' => 11 as char,
            n if is_oct(n) => {
                count += is_slice_oct(2) as usize + (is_slice_oct(2) && is_slice_oct(3)) as usize;
                slice[1..]
                    .iter()
                    .take(count - 1)
                    .fold(0, |acc, digit| acc * 8 + digit - b'0') as char
            }
            'x' => todo!(),
            'u' => todo!(),
            // Unspecified by POSIX; we ditto GNU.
            c => c, // TODO: Output warning
        }
    };
    out.push(escaped as u8);
    Ok(count)
}

fn parse_ident<'a>(lex: &mut Lexer<'a>, index: impl SliceIndex<[u8], Output = [u8]>) -> &'a str {
    accept_operator(lex);
    // SAFETY: The regex matching ensures it is ASCII.
    unsafe { str::from_utf8_unchecked(lex.slice().get_unchecked(index)) }
}

fn parse_float(lex: &mut Lexer<'_>) -> f64 {
    parse_ident(lex, ..).parse().unwrap_or(0.)
}

impl<'a> Identifier<'a> {
    fn without_namespace(lex: &mut Lexer<'a>) -> Self {
        Self {
            namespace: None,
            literal: parse_ident(lex, ..),
        }
    }

    fn with_namespace(lex: &mut Lexer<'a>) -> Self {
        // SAFETY: The regex matching ensures it is present and well-formed.
        let separator = unsafe { memchr(b':', lex.slice()).unwrap_unchecked() };
        Self {
            namespace: Some(parse_ident(lex, ..separator)),
            literal: parse_ident(lex, separator + 2..),
        }
    }
}

fn accept_expression(lex: &mut Lexer<'_>) {
    lex.extras = Context::AcceptExpression;
}

fn accept_operator(lex: &mut Lexer<'_>) {
    lex.extras = Context::AcceptOperator;
}

#[repr(transparent)]
#[derive(PartialEq, Eq, PartialOrd, Ord, Clone)]
pub struct Slice<'a>(Cow<'a, [u8]>);

impl Display for Slice<'_> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", String::from_utf8_lossy(&self.0).as_ref())
    }
}

impl Debug for Slice<'_> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "\"{self}\"")
    }
}

impl AsRef<[u8]> for Slice<'_> {
    fn as_ref(&self) -> &[u8] {
        &self.0
    }
}
